### ISSUE TITLE
Dataset Link Expired

### ISSUE THREAD

**Issue by H-Hui2277** [HopLee6/VSCrowd#2]
The link [**OneDrive**](https://unimelbcloud-my.sharepoint.com/:f:/g/personal/haopengl1_student_unimelb_edu_au/ElPHq3MxN-NOo0WFMCPU6VQB8Ia8V9S7u2IdrczBHpDjWQ?e=dFJhdP) in the [README.md](README.md) has expired. Could you please provide a new link for dataset downloading?

**Comment by HopLee6** [comment]
The OneDrive link has been updated. Please take a look.

**Comment by H-Hui2277** [comment]
> The OneDrive link has been updated. Please take a look.

Got it! Thanks.
